added main logic for working with web
ArtemReizer/book-store pull request #2
Opened 2023-09-05 22:14 UTC by ArtemReizer

2023-09-06 09:40 UTC, IvanFadieiev requested changes
Great job! Some small details to change :)

2023-09-06 09:40 UTC, IvanFadieiev commented on src/main/java/com/app/bookstore/config/MapperConfig.java
> +@org.mapstruct.MapperConfig(
If we name this class as "MapperConfiguration" we can use @MapperConfig annotation

2023-09-06 09:40 UTC, IvanFadieiev commented on src/main/java/com/app/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new EntityNotFoundException("Can't save the book: " + book, e);
I think that this exception it's not accurate for this case, better create a new DataProcessingException for example

2023-09-06 09:40 UTC, IvanFadieiev commented on src/main/java/com/app/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new EntityNotFoundException("Cannot get book by id: " + id, e);
It's better to return Optional here and handle it on service layer

2023-09-07 08:21 UTC, IvanFadieiev approved these changes
Great job!

2023-09-08 14:08 UTC, vovasalyha approved these changes
GJ

2023-09-08 14:08 UTC, vovasalyha commented on pom.xml
> +		<version>3.1.2</version>
was that necessary to downgrade version of spring boot?

2023-09-10 18:39 UTC, merged