added Spring Data JPA, liquibase support, soft delete concept and missing endpoints
ArtemReizer/book-store pull request #3
Opened 2023-09-06 18:38 UTC by ArtemReizer

2023-09-07 12:30 UTC, OlegTuryk approved these changes

2023-09-08 14:38 UTC, vovasalyha requested changes
GJ. Please take a look on my comments. Also, resolve all merge conflicts before asking a review next time.

2023-09-08 14:38 UTC, vovasalyha commented on pom.xml
> +            <artifactId>spring-boot-starter</artifactId>
do you really need this dependency?

2023-09-08 14:38 UTC, vovasalyha commented on src/main/java/com/app/bookstore/repository/book/BookRepository.java
> +    Book getBookById(Long id);
you don't need this. findById which returns optional is the best choice.

2023-09-08 14:38 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
empty line

2023-09-18 14:47 UTC, vovasalyha approved these changes

2023-09-25 14:35 UTC, merged