added CustomGlobalExceptionHandler and validation in Dto
ArtemReizer/book-store pull request #4
Opened 2023-09-06 23:06 UTC by ArtemReizer

2023-09-07 10:37 UTC, IhorKalaur approved these changes
Everything works, but I would add informativeness to the message, and set a limit on the length of characters.

2023-09-08 15:57 UTC, vovasalyha requested changes
Good. Let's improve it a bit.

2023-09-08 15:57 UTC, vovasalyha commented on src/main/java/com/app/bookstore/dto/CreateBookRequestDto.java
>      private String title;
Add length (size) constraints to not catch an exception on repository level

2023-09-08 15:57 UTC, vovasalyha commented on src/main/java/com/app/bookstore/dto/CreateBookRequestDto.java
>      private String author;
same here

2023-09-08 15:57 UTC, vovasalyha commented on src/main/java/com/app/bookstore/exceptions/CustomGlobalExceptionHandler.java
> +        Map<String, Object> body = new LinkedHashMap<>();
better create a class for error response body (or use some classes created by spring)

2023-09-25 15:07 UTC, vovasalyha approved these changes

2023-09-25 15:16 UTC, merged