added security
ArtemReizer/book-store pull request #6
Opened 2023-09-13 18:59 UTC by ArtemReizer

2023-09-14 12:11 UTC, OleksandrSaven approved these changes
Looks good! see my comments

2023-09-14 12:11 UTC, OleksandrSaven commented on src/main/java/com/app/bookstore/model/User.java
> +            inverseJoinColumns = @JoinColumn(name = "role_id"))
In such case will be good to use  @ToString.Exclude and @EqualsAndHashCode.Exclude annotation

2023-09-14 12:11 UTC, OleksandrSaven commented on src/main/resources/db/changelog/changes/04-create-users-table.yaml
> +                  type: boolean
Add default value

2023-09-14 16:00 UTC, vovasalyha requested changes
GJ, but add constraints to the linking table

2023-09-14 16:00 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/03-create-user-role-table.yaml
> +              - column:
Add constraints to this table. Primary key (user_id, role_id) and foreign keys for both columns

2023-09-15 12:08 UTC, andrii-hoienko requested changes
Nice, I left minor comments

2023-09-15 12:08 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/security/CustomUserDetailsService.java
> +                new UsernameNotFoundException("User not found with email: " + username));
Not found with email or with username?

2023-09-15 12:08 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/security/JwtAuthenticationFilter.java
> +    private static final int TOKEN_START_INDEX = 7;
It is possible to use BEARER_TOKEN.length instead of constant

2023-09-15 12:08 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/security/JwtAuthenticationFilter.java
> +    private static final String BEARER_TOKEN = "Bearer ";
Bad constant naming, it is not a token, it is some string which is not represents token

2023-09-15 12:08 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/security/JwtUtil.java
> +
```suggestion
```

2023-09-15 12:08 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/service/impl/UserServiceImpl.java
> +            throw new RegistrationException("The user is already registered");
add some details to error message

2023-09-26 07:07 UTC, nacenik approved these changes
LGTM! 👍

2023-09-26 07:08 UTC, merged