added CategoryController and other functionality
ArtemReizer/book-store pull request #7
Opened 2023-09-19 01:30 UTC by ArtemReizer

2023-09-19 08:09 UTC, ohatsenko approved these changes

2023-09-19 15:48 UTC, vovasalyha requested changes
GJ. Let's improve it a bit

2023-09-19 15:48 UTC, vovasalyha commented on src/main/java/com/app/bookstore/model/Category.java
> +    @NotNull
Please replace it with @Column(nullable = false), they have one significant difference which is imprtant

2023-09-19 15:48 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/09-insert-fiction-book.yaml
> +              - column: {name: book_id, value: 1}
Better compute the value of id by ISBN for example, to elimitate the posibility that book with id 1 is absent, the same for category

2023-09-26 12:31 UTC, andrii-hoienko approved these changes
GJ!

2023-09-26 12:31 UTC, merged