Added Order entity and its implementation
ArtemReizer/book-store pull request #9
Opened 2023-09-25 13:16 UTC by ArtemReizer

2023-09-26 08:48 UTC, OleksandrSaven requested changes
Good solution. Let's improve it a bit

2023-09-26 08:48 UTC, OleksandrSaven commented on src/main/java/com/app/bookstore/service/impl/OrderServiceImpl.java
> +        Order order = orderRepository.findOrderItemsByOrderId(orderId);
in this method, you will extract all items, but you need only that belong to the current user

2023-09-26 08:48 UTC, OleksandrSaven commented on src/main/java/com/app/bookstore/service/impl/OrderServiceImpl.java
> +        Order order = orderRepository.findOrderItemsByOrderId(orderId);
in this case I would check if the orderId belongs to this user

2023-09-26 12:41 UTC, andrii-hoienko requested changes
GJ! Let`s improve your solution a bit

2023-09-26 12:41 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/controller/OrderController.java
> +    public OrderDto placeOrder(@RequestBody PlaceOrderRequestDto placeOrderRequestDto) {
```suggestion
    public OrderDto placeOrder(@RequestBody @Valid PlaceOrderRequestDto placeOrderRequestDto) {
```

2023-09-26 12:41 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/model/CartItem.java
> +    @OneToOne(fetch = FetchType.EAGER)
What is the reason to change fetchType?

2023-09-26 12:41 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/model/OrderItem.java
> +
```suggestion
```

2023-09-26 12:41 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/service/impl/OrderServiceImpl.java
> +        if (Objects.equals(order.getUser().getId(), user.getId())) {
1. Code duplication 2. It is possible to make such check on BD level, just do not fetch order which is not owned by user

2023-09-26 12:41 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/service/impl/OrderServiceImpl.java
> +    private ShoppingCart getShoppingCart() {
It is cart service responsibility

2023-09-26 12:41 UTC, andrii-hoienko commented on src/main/java/com/app/bookstore/service/impl/OrderServiceImpl.java
> +        orderItemRepository.saveAll(orderItems);
Is it possible to use cascade to save orderItem together with order by one statement?

2023-09-26 12:41 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/13-create-orders-table.yaml
> +                  name: user_id
fk constraint?

2023-09-28 07:36 UTC, nacenik approved these changes
LGTM! 👍

2023-09-28 07:36 UTC, nacenik commented on src/main/java/com/app/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public void clear(ShoppingCart cart) {
I'd recommend you put Transactional here. You can have a lot of items, and it could take a while to delete all of them

2023-09-28 08:51 UTC, merged